version: 2

models:
  - name: stg_telegram
    description: "Staged telegram messages with calculated fields."
    columns:
      - name: message_id
        tests:
          - unique
          - not_null

  - name: dim_channels
    description: "Dimension table for Telegram channels."
    columns:
      - name: channel_key
        tests:
          - unique
          - not_null
      - name: channel_name
        tests:
          - not_null

  - name: dim_dates
    description: "Date dimension table."
    columns:
      - name: date_key
        tests:
          - unique
          - not_null

  - name: fct_messages
    description: "Fact table for message metrics."
    columns:
      - name: message_id
        tests:
          - unique
          - not_null
      - name: channel_key
        tests:
          - not_null
          - relationships:
              to: ref('dim_channels')
              field: channel_key

  - name: fct_image_detections
    description: "Fact table for AI image analysis results."
    columns:
      - name: message_id
        tests:
            - not_null
            # Uniqueness might not be strictly true if one message has multiple images or detections? 
            # But per current logic, one image per message is common, so unique usually holds.
            # If multiple images, message_id repeats. Let's assume unique for now or just not_null.
            # The feedback explicitly asked for tests, generally unique/not_null are standard.
            # Given scraper saves one image per message (message_id.jpg), it should be unique.
            - unique
